changelog:
  categories:
    - title: "Breaking changes"
      labels:
        - "breaking change"
    - title: "New features"
      labels:
        - "enhancement"
    - title: "Bug fixes"
      labels:
        - "bug"
    - title: "Dependency updates"
      labels:
        - "renovate"
    - title: "Documentation"
      labels:
        - "documentation"
    - title: "Other changes"
      labels:
        - "*"
